language: node_js
node_js:
  - "6"
  - "8"
  - "node"
  - "lts/*"

addons:
  apt:
    packages:
      - google-chrome-stable
    firefox: 'latest'

cache: yarn
install: yarn --frozen-lockfile

before_script:
  - export DISPLAY=:99; sh -e /etc/init.d/xvfb start; sleep 3
